version: "3.9"
services:

  db:
    container_name: kanalservis_db
    image: postgres:14.0-alpine
    restart: 'always'
    command: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker -d docker" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - TZ=Europe/Moscow
    env_file:
      - variables.env
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m flask run --host=0.0.0.0 --port=8000
    restart: "no"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main.py
      - TZ=Europe/Moscow
    env_file:
      - variables.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres: