version: "3.9"
services:

  db:
    container_name: kanalservis_db
    image: postgres:14.0-alpine
    restart: 'always'
    command: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker -d docker" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - variables.env
    ports:
      - "5432:5432"

  app:
    container_name: kanalservis_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'no'
    environment:
      - TZ=Europe/Moscow
    env_file:
      - variables.env
    volumes:
      - ./app:/app
    command:
      python main.py
    depends_on:
      - db

volumes:
  postgres: